CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Hawksbill        GCCTCTAGCAACA-ACAAGTATTAGAGGTAATGCCTGCCCAGTGACACTGTTAAACGGCC
Loggerhead       GCCTCTAGCAACA-ATAAGTATTAGAGGTAATGCCTGCCCAGTGACACTGTTAAACGGCC
Olive            -----------------------------------------GTGAC-CTGTTAAACGGCC
Kemp’s           GCCTCTAGCAACA-ACAAGTATTAGAGGTAATGCCTGCCCAGTGACACTGTTAAACGGCC
Leatherback      GCCCCTAGCAATA-ACAAGTATTAGGGGTAATGCCTGCCCAGTGACACTGTTAAACGGCC
Flatback         GCCTCTAGCAACACATAAGTATTAGAGGTAATGCCTGCCCAGTGACACTGTTAAACGGCC
Green            --------------------------------------------------------GGCC
                                                                         ****

Hawksbill        GCGGTATCCTAACCGTGCAAAGGTAGCGTAATCACTTGTCTTTTAAATAAAGACTAGAAT
Loggerhead       GCGGTATCCTAACCGTGCAAAGGTAGCGTAATCACTTGTCTTTTAAATAAAGACTAGAAT
Olive            GCGGTATCCTAACCGTGCAAAGGTAGCGTAATCACTTGTCTTC--AATAAAGACTAGAAT
Kemp’s           GCGGTATCCTAACCGTGCAAAGGTAGCGTAATCACTTGTCTTTTAAATAAAGACTAGAAT
Leatherback      GCGGTATCCTAACCGTGCAAAGGTAGCGTAATCACTTGTCTTTTAAATAAAGACTAGAAT
Flatback         GCGGTATCCTAACCGTGCAAAGGTAGCGTAATCACTTGTCTTTTAAATAAAGACTAGAAT
Green            GCGGTATCCTAACCGTGCAAAGGTAGCGTAATCACTTGTCTTTTAAATAAAGACTAGAAT
                 ******************************************   ***************

Hawksbill        GAATGGCCAAACGAGGTTCCACCTGTCTCTTACAAACAATCAGTGAAATTGGTCTCCCCG
Loggerhead       GAATGGCCAAACGAGGTTCCACCTGTCTCTTACAAACAATCAGTGAAATTGGTCTTCCCG
Olive            GAATGGCCAAACGAGGTTCCACCTGTCTCTTACAAACAATCAGTGAAATTGGTCCCCCCG
Kemp’s           GAATGGCCAAACGAGGTTCCACCTGTCTCTTACAAACAATCAGTGAAATTGGTCTCCCCG
Leatherback      GAATGGCCAAACGAGGTTCTACCTGTCTCTTACAAACAATCAGTGAAATTGATCTCCCCG
Flatback         GAATGGCCAAACGAGGTTCCACCTGTCTCTTACAAATAATCAGTGAAATTGATCTCCCCG
Green            GAATGGCCAAACGAGGTTCTACCTGTCTCTTACAAACAATCAGTGAAATTGATCTCCCCG
                 ******************* **************** ************** **  ****

Hawksbill        TGCAAAAGCGAGGATAGCACTATAAGACGAGAAGACCCTGTGGAACTTTAAATATAAATC
Loggerhead       TGCAAAAGCGGGAATAACACTATAAGACGAGAAGACCCTGTGGAACTTCAAATATAAATC
Olive            TGCAAAAGCGAGGATAACATTATAAGACGAGAAGACCCTGTGGAACTTTAAATATAAATC
Kemp’s           TGCAAAAGCGGGGATAACATTATAAGACGAGAAGACCCTGTGGAACTTTAAATATAAATC
Leatherback      TGCAAAAGCAGGGATGATACTATAAGACGAGAAGACCCTGTGGAACTTTAAATACAGATC
Flatback         TGCAAAAGCGGGAATAACACTATAAGACGAGAAGACCCTGTGGAACTTTAAATACAAATC
Green            TGCAAAAGCGGGGATAACACTATAAGACGAGAAGACCCTGTGGAACTTTAAatacagatc
                 *********  * **   * **************************** ***** * ***
